
### GET CERTIFICADOS 
GET http://localhost:9000/certificado

### GET CERTIFICADOS BY TIENDA
GET http://localhost:9000/certificado/tienda/48628566-9d7a-44ba-9440-0acc6120fddb

### GENERAR CERTIFICADO LE
POST http://localhost:9000/certificado/generar
Content-Type: application/json

{
  "tiendaId": "48628566-9d7a-44ba-9440-0acc6120fddb",
  "cantidad": 31,
  "fechaEmision": "04-02-2026",
  "tipo": "DH"
}

### GENERAR CERTIFICADO DH
POST http://localhost:9000/certificado/generar
Content-Type: application/json

{
  "tiendaId": "23351b5f-536e-4837-9b5d-62f33667c2d4",
  "cantidad": 11,
  "fechaEmision": "04-02-2026",
  "tipo": "DH"
}

### DELETE CERTIFICADO
DELETE http://localhost:9000/certificado/cc11dd22-ee33-ff44-gg55-hh6677889900