### GET
GET http://localhost:9000/tienda

### GETBYID
GET http://localhost:9000/tienda/2bca3e7b-3e54-4e97-85ed-7070bcf2cd2a

### CREATE TIENDA
POST http://localhost:9000/tienda
Content-Type: application/json

{
  "nombre": "Alamos 1 Ves",
  "direccion": "Av. Siempre Viva 123",
  "distrito": "Miraflores",
  "provincia": "Lima",
  "departamento": "Lima",
  "asociacionId": "0e8d0d51-bec9-4814-a7fa-ff0508f606b1"
}

### UPDATE TIENDA
PUT http://localhost:9000/tienda/31ae7fcf-d405-4ef6-b490-ac3d4b7a0609
Content-Type: application/json

{
  "nombre": "Plaza Vea Cusco",
  "direccion": "Av. Cusco",
  "distrito": "Cusco",
  "provincia": "Cusco",
  "departamento": "Cusco"
}

### DELETE
DELETE http://localhost:9000/tienda/990d55ce-25ec-42c3-9449-92711f4c1919
